name: bloc_state_machine_prototype
description: Prototype for State Machine for BLoC proposal
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  lints: ^1.0.0

dependencies: 
  bloc: ^8.0.2
